// my-ecommerce-api/gameData.js

exports.fakeGames = [
  {
    id: 1,
    name: "Cyberpunk 2077",
    price: 59.99,
    platform: ["PC", "PlayStation 5"],
    genre: ["Nhập vai", "Hành động"],
    image: "/cyberpunk.jpg",
    description:
      "Cyberpunk 2077 là một game nhập vai hành động-phiêu lưu trong thế giới mở...",
  },
  {
    id: 2,
    name: "Elden Ring",
    price: 69.99,
    platform: ["PlayStation 5", "PC"],
    genre: ["Hành động", "Nhập vai"],
    image: "/eldenring.jpg",
    description:
      "Vùng đất Lands Between đang chờ đợi bạn. Hãy trỗi dậy, hỡi Tarnished...",
  },
  {
    id: 3,
    name: "Starfield",
    price: 69.99,
    platform: ["Xbox Series X", "PC"],
    genre: ["Nhập vai"],
    image: "/starfield.jpg",
    description:
      "Starfield là vũ trụ mới đầu tiên sau hơn 25 năm của Bethesda Game Studios...",
  },
  {
    id: 4,
    name: "Stardew Valley",
    price: 14.99,
    platform: ["PC", "Nintendo Switch"],
    genre: ["Mô phỏng", "Nhập vai"],
    image: "/stardew.jpg",
    description:
      "Bạn đã được thừa hưởng trang trại cũ của ông nội ở Stardew Valley...",
  },
  {
    id: 5,
    name: "Zelda: Tears of the Kingdom",
    price: 59.99,
    platform: ["Nintendo Switch"],
    genre: ["Phiêu lưu", "Hành động"],
    image: "/zelda.jpg",
    description:
      "Một cuộc phiêu lưu sử thi trên khắp vùng đất và bầu trời Hyrule đang chờ đợi...",
  },
  {
    id: 6,
    name: "Red Dead Redemption 2",
    price: 39.99,
    platform: ["PC", "PlayStation 4"],
    genre: ["Hành động", "Phiêu lưu"],
    image: "/rdr2.jpg",
    description: "Câu chuyện về Arthur Morgan và băng đảng Van der Linde...",
  },
  {
    id: 7,
    name: "Hogwarts Legacy",
    price: 69.99,
    platform: ["PlayStation 5", "PC", "Xbox Series X"],
    genre: ["Nhập vai", "Phiêu lưu"],
    image: "/hogwarts.jpg",
    description:
      "Hogwarts Legacy là một game nhập vai hành động trong thế giới mở...",
  },
  {
    id: 8,
    name: "God of War Ragnarök",
    price: 69.99,
    platform: ["PlayStation 5", "PlayStation 4"],
    genre: ["Hành động", "Phiêu lưu"],
    image: "/godofwar.jpg",
    description: "Kratos và Atreus phải hành trình đến từng Cửu Giới...",
  },
  {
    id: 9,
    name: "Resident Evil 4 Remake",
    price: 59.99,
    platform: ["PlayStation 5", "PC", "Xbox Series X"],
    genre: ["Kinh dị", "Hành động"],
    image: "/re4.jpg",
    description: "Phiên bản làm lại của kinh điển Resident Evil 4 với đồ họa hiện đại...",
  },
  {
    id: 10,
    name: "Amnesia: The Dark Descent",
    price: 19.99,
    platform: ["PC"],
    genre: ["Kinh dị"],
    image: "/amnesia.jpg",
    description: "Bạn thức dậy trong một lâu đài tối tăm mà không nhớ gì về quá khứ...",
  },
  {
    id: 11,
    name: "Outlast",
    price: 29.99,
    platform: ["PC", "PlayStation 4"],
    genre: ["Kinh dị"],
    image: "/outlast.jpg",
    description: "Bạn là một nhà báo điều tra vào bệnh viện tâm thần Mount Massive...",
  },
  {
    id: 12,
    name: "The Evil Within 2",
    price: 39.99,
    platform: ["PC", "PlayStation 4", "Xbox One"],
    genre: ["Kinh dị", "Hành động"],
    image: "/evilwithin2.jpg",
    description: "Thám tử Sebastian Castellanos quay trở lại thế giới kinh hoàng...",
  },
];
